# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

attach_pool <- function(conn, host, port, db, user, password, workers) {
    invisible(.Call(`_pgpromise_attach_pool`, conn, host, port, db, user, password, workers))
}

collect_async_callback <- function(conn, query, resolve, reject) {
    invisible(.Call(`_pgpromise_collect_async_callback`, conn, query, resolve, reject))
}

